### ISSUE TITLE
[ui-upgrade]: Upgrade Footer

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [SyedImtiyaz-1/GetTechProjects#168]
### Change this Footer - 
![image](https://github.com/SyedImtiyaz-1/PreciousServices/assets/121503426/242e4329-8223-4ee5-b68b-3f6ad2c7e2a4)

- Add a familiar footer as per UI, and please drop a screenshot.
- Also don't forget to link the footer to all the pages.

**Comment by sahashorha** [comment]
I want to work in this issue can you assign me

**Comment by SyedImtiyaz-1** [comment]
Wait if @Durgeshsejekar can't able to do it then I'll assign you.

**Comment by DurgaPrasad-R** [comment]
@SyedImtiyaz-1 Is this issue still open?

**Comment by kashnx** [comment]
I want to work on this issue.
