### ISSUE TITLE
[BUG]:  Making Logo fixed in Carrer Page

### ISSUE THREAD

**Issue by SadafKausar2025** [SyedImtiyaz-1/GetTechProjects#282]
**Describe the bug**
In Carrer Page the top left  logo is not fixed or not properly visible

![Screenshot (1794)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137484958/a3b121f0-f433-47ea-9b5f-ba490e6ea18b)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Aditi-Gopinath** [comment]
Please assign me this issue under GSSOC'24 @SyedImtiyaz-1
