### ISSUE TITLE
[BUG]: "Contact" Link in the header redirects to Home Page Instead of Contact Page

### ISSUE THREAD

**Issue by Samridhi002** [SyedImtiyaz-1/GetTechProjects#283]
**Describe the bug**
The "Contact" link in the navigation bar of the header section in "Career Page" is currently redirecting users to the home page instead of the intended contact page. This affects the user experience as users are unable to access the contact information or form directly.

**To Reproduce**
1. Navigate to the Career Page of the site.
2. Click on the "Contact" link in the navigation bar of the header section.
3. Observe that you are redirected to the home page instead of the contact page.

**Expected Behavior:**
Clicking on the "Contact" link should redirect users to the contact page where they can find the contact information or form.

**Actual Behavior:**
Clicking on the "Contact" link redirects users to the home page.

**Screenshots**
![Screenshot (19)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/169380578/2a49330f-2a4c-4b5c-ab75-3b6eb90d4a2d)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

Hii PA,
I can solve this issue once you assign me under GSSoC'24. Thank You!

**Comment by Aditi-Gopinath** [comment]
Please assign me this issue under GSSOC'24 @SyedImtiyaz-1
