### ISSUE TITLE
link issue in footer 

### ISSUE THREAD

**Issue by SakiraAli1115** [SyedImtiyaz-1/GetTechProjects#285]
Hello PA,

Mail Address
 Please assign me this issue !

![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/169131830/6f7316e2-a79b-4db6-930e-e5bef7b26cde)

**Comment by DhruvJohri** [comment]
please assign me this issue @SyedImtiyaz-1

**Comment by Aditi-Gopinath** [comment]
Please assign me this issue under GSSOC'24 @SyedImtiyaz-1
