### ISSUE TITLE
[feat]: Adding Password Manager App

### ISSUE THREAD

**Issue by SadafKausar2025** [SyedImtiyaz-1/GetTechProjects#286]
**Describe the bug**
This App Manage the password very safely
In this project MongoDB is used as a  Backend which saves all website name and usename and password

![Screenshot (1795)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137484958/624ac8f5-48e2-4c5c-b29c-b64bb87aaca4)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SadafKausar2025** [comment]
Hey @SyedImtiyaz-1 
can you Please assign me this issue?

**Comment by SakiraAli1115** [comment]
Hello PA,
@SyedImtiyaz-1
 
Please assign me this issue!
