### ISSUE TITLE
[BUG]: From Carrer Page Navbar links[Project and Contact] is not directing to correct site

### ISSUE THREAD

**Issue by SadafKausar2025** [SyedImtiyaz-1/GetTechProjects#287]
**Describe the bug**
I think This issue can make problems when anyone is in the career page and wants to go back to the project and contact page
so there is need to correct it

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SadafKausar2025** [comment]
Hey @SyedImtiyaz-1 
can you please assign me this issue?

**Comment by Maheshwari-Love** [comment]
@SyedImtiyaz-1 can you please assign me this task?
