### ISSUE TITLE
[feat]: Adding Scroll to Top button in Project Page

### ISSUE THREAD

**Issue by SadafKausar2025** [SyedImtiyaz-1/GetTechProjects#290]
**Describe the feature**
when there will be more and more projects then it is necessary to have scroll to top button/icon in down right corner of the page

screenshot is not required

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SadafKausar2025** [comment]
hey @SyedImtiyaz-1 
Syed Imtiyaz Ali can you please assign me this issue?

**Comment by Mukunda2000** [comment]
Hey @SyedImtiyaz-1 please assign me this task I want to do this task
