### ISSUE TITLE
[feat]: Adding Favicon and Tittle name in every Page

### ISSUE THREAD

**Issue by SadafKausar2025** [SyedImtiyaz-1/GetTechProjects#295]
**Describe the bug**
the favicon is not related to it projects, so there is a need of setting the favicon
and also other page is not showing the correct title name and favicon 

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by DhruvJohri** [comment]
please assign me this issue @SyedImtiyaz-1

**Comment by kashnx** [comment]
Please assign me this issue.

**Comment by Tarungupta18** [comment]
please assign me this issue
