### ISSUE TITLE
[feat]: Adding Currency Converter App

### ISSUE THREAD

**Issue by SadafKausar2025** [SyedImtiyaz-1/GetTechProjects#297]
**Describe the feature**
This is the small project Which can convert any currency to every other currency in this world

the tech stack used are HTML , CSS , JS 

![Screenshot (1799)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137484958/30143a08-980d-411e-b0b9-76932bcd284d)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Tanishka023** [comment]
Hey!! I am excited to contribute, Please assign this to me under GSSoC'24. @SyedImtiyaz-1
