### ISSUE TITLE
[feat]: Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [SyedImtiyaz-1/GetTechProjects#299]
**Describe the feature**
I would be adding a preloader to increase user attention . It would be matching with the theme of UI . It would contain a svg animation 

**Expected behavior**
A preloader should render until the files are being loaded

**Additional context**
Kindly assign it to me under GSSoC'24

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
Add a attractive pre loader 📌
