### ISSUE TITLE
[feat]: Adding a Tic Tac Toe game app.

### ISSUE THREAD

**Issue by Ishitamukherjee2004** [SyedImtiyaz-1/GetTechProjects#301]
**Screenshots**

https://github.com/SyedImtiyaz-1/GetTechProjects/assets/138589633/32d32f3b-11c8-463d-b6bd-b4703c277870

**Additional context**
This tic tac toe game is made using HTML, CSS and Javascript.
This is a user friendly game, anyone can easily play this.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Ishitamukherjee2004** [comment]
Hello @SyedImtiyaz-1 
Please assign this issue to me.

**Comment by Aditi-Gopinath** [comment]
Please assign me this issue under GSSOC'24 @SyedImtiyaz-1

**Comment by SyedImtiyaz-1** [comment]
Please add another game.
Closing this issue.
