### ISSUE TITLE
Adding the weight converter application

### ISSUE THREAD

**Issue by ChaitanyaLonarkar** [SyedImtiyaz-1/GetTechProjects#305]
Adding the weight converter application

I want to add weight converter application which is made by using Html, CSS and Js .
Which convert the one unit to another unit.

![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/110454138/d882f6ff-ec3c-44d7-9a11-0232c4387474)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SadafKausar2025** [comment]
Hey @ChaitanyaLonarkar 
Your PR is merged then please close this issue.

**Comment by ChaitanyaLonarkar** [comment]
Close
