### ISSUE TITLE
Improving the Projects Cards display and animation 

### ISSUE THREAD

**Issue by somrima-09** [SyedImtiyaz-1/GetTechProjects#306]
@SyedImtiyaz-1 

1. Go to Project tab
2. Click on it
3. Scroll down to
4. Requesting to improve the cards animation and fronts.

PA Please Assign me this issue.

![Screenshot_20240527_160052_Chrome](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137212792/4f7f9c82-9f3e-4811-a782-776d477fb3e5)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Adv1919** [comment]
Please assign me this issue @SyedImtiyaz-1 
I would like to work on it under Gssoc'24

**Comment by somrima-09** [comment]
Please merge my issue.
I worked hard and given time to do this work efficiently.

Thank you.
**Please merge it!**
