### ISSUE TITLE
Home Page UI upgradation

### ISSUE THREAD

**Issue by ChaitanyaLonarkar** [SyedImtiyaz-1/GetTechProjects#307]
I want to enhance the home page UI and add more styling.
Enhancing the fonts, colors and etc... Which add the attractiveness in this website.

![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/110454138/fc4d1e33-59db-4ea4-bcb1-15bedbe8ab42)

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
Kindly find another issue.
