### ISSUE TITLE
chore: project addition by Bhavy : I want to add Microsoft Clone

### ISSUE THREAD

**Issue by zalabhavy** [SyedImtiyaz-1/GetTechProjects#418]
**Screenshots**
![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/126322584/194aa899-add2-45fb-818f-ddda54c9a73a)

**Additional context**
This Clone is responsive and made with  css ,tailwind css and html.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SadafKausar2025** [comment]
Hi @zalabhavy 
this project is already there in the project page
please choose another project

**Comment by zalabhavy** [comment]
Ok i am closeing this !
