### ISSUE TITLE
chore: Adding Calculator project

### ISSUE THREAD

**Issue by harikasayani** [SyedImtiyaz-1/GetTechProjects#430]
**Describe the bug**
I want to add calculator project

**To Reproduce**

**Additional context**
I am GSSOC'24 Contributor.
Please assign me this task.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SadafKausar2025** [comment]
![Screenshot (1838)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/137484958/c5f3efb0-7f0a-428c-9643-7e72e40e105d)

hey @SyedImtiyaz-1 
can you please assign me this issue?

**Comment by Tarungupta18** [comment]
hey @SyedImtiyaz-1 
please assign me this issue? 
I am expert in this field
![calcutor](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/125756220/fd8cf53a-fa8c-4443-9739-fbcd80ead641)
