### ISSUE TITLE
[feat]: Adding Rock paper Scissor game

### ISSUE THREAD

**Issue by harinisayani** [SyedImtiyaz-1/GetTechProjects#432]
**Describe the bug**
Adding Rock paper Scissor game 

**To Reproduce**

**Screenshots**

**Additional context**
I am GSSOC'24 contributor.
I want to work on this issue.
Please assign me this issue.

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
Already someone is working on this.
