### ISSUE TITLE
[BUG]: payment gate way is not working, added razorpay gateway with UI using tailwind

### ISSUE THREAD

**Issue by Tarungupta18** [SyedImtiyaz-1/GetTechProjects#488]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot (54)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/125756220/bf8c25da-0e9c-4bec-86c9-1090949ea9e5)
![rozerpay](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/125756220/66ef5d07-87ed-4e00-9b7e-b2eb740aed01)

**Additional context**

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ] I have checked the existing issues
- [ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [ ] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [ ] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
I'm going to update by myself.
We are focusing now for adding projects.
