### ISSUE TITLE
Full Stack App : Netflix clone 

### ISSUE THREAD

**Issue by Yashgabani845** [SyedImtiyaz-1/GetTechProjects#489]
**Describe the bug**
current netflix clone is is done by html,css,js,rapid api in your project 
i have proper netflix clone i have done in last one month using 

- Html,css,js
- Node-express
- Mongodb cloud(so no tesion of setup)
- firebase cloud storage(for storing videos)
- stripe for payment gateway

**Screenshots**
![Screenshot (257)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/127788321/d3a4e4cb-8624-4f67-bddf-a3b34fad7d38)
![Screenshot (259)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/127788321/3811f8b0-8144-4fc3-807a-b2be0054d93a)
![Screenshot (260)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/127788321/5a0adaf9-a870-44e6-802e-7a1a8c581569)
![Screenshot (261)](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/127788321/64984bf1-556c-4275-90b5-a62dfceba197)

**Additional context**
i will be great increment in your project i swear , it is my best project

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [x] I have checked the existing issues
- [x] [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [x] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [x] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by Yashgabani845** [comment]
@SyedImtiyaz-1  please assign me this issue

**Comment by SadafKausar2025** [comment]
hi @Yashgabani845 
this project is already there in project page
please choose another project which is not present

**Comment by Yashgabani845** [comment]
@SadafKausar2025  i have metioned that in my issue please read issue propely then comment

**Comment by Yashgabani845** [comment]
@SadafKausar2025  read issue properly i have mentioned these things that are going to change
