### ISSUE TITLE
Adding a `Back to top` button

### ISSUE THREAD

**Issue by Ketanop321** [SyedImtiyaz-1/GetTechProjects#503]
**Describe the bug**
onclicking back to top button it will go to top of the page ,  increasing use ecperience

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [ ✅] I have checked the existing issues
- [✅ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [✅ ] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [✅ ] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/ketanop321)

**Comment by SyedImtiyaz-1** [comment]
Already added.
