### ISSUE TITLE
[feat]:Preloader

### ISSUE THREAD

**Issue by Anjaliavv51** [SyedImtiyaz-1/GetTechProjects#533]
**Describe the bug**
No bug addition of Preloader.

**To Reproduce**

**Expected behavior**
Preloader only appears at the time of Loading a page , which gives clarity to the user that the webpage is loading.

**Screenshots**
Feature
Preloader

https://github.com/SyedImtiyaz-1/GetTechProjects/assets/154777864/7b226950-97da-49e9-9526-d98b7f12a52e

**Additional context**

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [X] I have checked the existing issues
- [X]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [X] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [X] I want to work on this issue

Connect with me on [Linkedin](https://linkedin.com/in/imtiyaz-sde)
Let's Connect 1:1 - [Click Here]https://topmate.io/syedimtiyazali

**Comment by SyedImtiyaz-1** [comment]
Hello,
Can you please add a simple preloader

**Comment by Anjaliavv51** [comment]
Okay
