### ISSUE TITLE
[BUG]: alignment is wrong

### ISSUE THREAD

**Issue by Gamerking177** [SyedImtiyaz-1/GetTechProjects#562]
**Describe the bug**
alignment is wrong

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/130808542/8863b27c-21bc-4c20-880c-9f554793fecf)

**Additional context**

🌟 **Note**: Please make sure to complete all the required tasks before submitting your issue/PR.

- [✅] I have checked the existing issues
- [✅ ]  [Give a Star](https://github.com/SyedImtiyaz-1/PreciousServices) ⭐
- [✅] Follow - [Project Admin](https://github.com/SyedImtiyaz-1/)
- [✅] I want to work on this issue

**Comment by Shruti192903** [comment]
Assign it with gssoc tag , level and assign to me so that I can work on it.
