### ISSUE TITLE
[Feature Request]: Add a Car Racing  

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [SyedImtiyaz-1/GetTechProjects#646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a Car Racing Extension 

### Use Case

This will give joy to the users .

### Add ScreenShots

https://github.com/SyedImtiyaz-1/GetTechProjects/assets/118350936/64368d70-db8a-4be6-8bdd-0ad83086e136

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SyedImtiyaz-1** [comment]
Hello,
kindly add a correct path and public drive link in json.
Also add your project in projects folder.
