### ISSUE TITLE
[feat]: Add QR Code Generator

### ISSUE THREAD

**Issue by sarayusreeyadavpadala** [SyedImtiyaz-1/GetTechProjects#648]
@SyedImtiyaz-1 I would like to contribute to this repository by adding QR code generator. This QR code generator can generate QR code for text, contact information, WIFI network details and URL's. And will provide customization options like size, color and error correction level. And will provide download option with png extension.

I am a GSSoC contributor. 
Could you please assign this issue to me?

**Comment by sarayusreeyadavpadala** [comment]
@SyedImtiyaz-1 Could you please assign this issue to me and label it as gssoc?

**Comment by SyedImtiyaz-1** [comment]
Already added

**Comment by sarayusreeyadavpadala** [comment]
@SyedImtiyaz-1 why did you close this issue?

**Comment by sarayusreeyadavpadala** [comment]
I didn't see the project related to customizable QR Code Generator @SyedImtiyaz-1
