### ISSUE TITLE
[Feature Request]: add new project- University website

### ISSUE THREAD

**Issue by suma30** [SyedImtiyaz-1/GetTechProjects#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add a simple and new project that is a university / college website,
built using HTML, CSS and JS
please can you assign me this issue @SyedImtiyaz-1 under GSSOC

### Use Case

This website would be beneficial for those looking for a simple website for their institutes

### Add ScreenShots

![Screenshot 2024-06-04 220403](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/112741893/0cdbd914-1776-4d4f-901d-ac9dc8dc5bd8)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by suma30** [comment]
@SyedImtiyaz-1 can you please assign me this issue
/assign

**Comment by SyedImtiyaz-1** [comment]
Hello,
kindly add a correct path and public drive link in json.
Also add your project in projects folder.

**Comment by suma30** [comment]
@SyedImtiyaz-1 could you please assign me the issue ,I think you have assigned it to the wrong id

**Comment by sanjay-kv** [comment]
@SyedImtiyaz-1 I just noticed on a random checks, 
The payment option on the repo is not working. 

@suma30 I fixed the assign issue, as I already had the access to the repo. Keep contributing and let @SyedImtiyaz-1 know if there is any way you can add more features so the project can be better. 

![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/30715153/0bfa3117-3366-457c-90c3-cc05f409450a)
