### ISSUE TITLE
[Bug]: alignment of text

### ISSUE THREAD

**Issue by dhairyagothi** [SyedImtiyaz-1/GetTechProjects#664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Text is not properly alligned in one line i can fix it please assign the task to me under gssoc

### Expected behavior

text should be aligned in one line

### Add ScreenShots

![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/142989448/2cde0fa7-c98d-404e-936a-d6a6fd959894)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SyedImtiyaz-1** [comment]
![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/121503426/1b337d12-b583-4452-b2ae-a55199fe2c13)

Already fixed.
