### ISSUE TITLE
[Feature Request]: Add To-do List project

### ISSUE THREAD

**Issue by aindrelasaha** [SyedImtiyaz-1/GetTechProjects#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add to-do list project made by me
![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/126545390/e35a9675-4f21-446f-964b-520fc13eab1b)

### Use Case

My to-do list project link--> https://todo-list-by-aindrela.vercel.app/

### Add ScreenShots

![image](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/126545390/7b21427d-8ac7-408d-b7ef-4e50f8852f97)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SyedImtiyaz-1** [comment]
@aindrelasaha Add another proejct, it's already added.
