### ISSUE TITLE
[Bug]:  email should be in lower case

### ISSUE THREAD

**Issue by SadiyaTahsin29** [SyedImtiyaz-1/GetTechProjects#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot 2024-06-06 130955](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/146445777/331be381-5ede-4eed-894b-0fd76b34062c)
there should be an improvement in the grammar also , also I would suggest adding founder section

### Expected behavior

 improvement in the footer text and layout. 

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SyedImtiyaz-1** [comment]
@SadiyaTahsin29 Why closed ?
