### ISSUE TITLE
[Feature Request]: Add Flappy Bird Game

### ISSUE THREAD

**Issue by AsmitaMishra24** [SyedImtiyaz-1/GetTechProjects#829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to add the Flappy Bird game, providing a clean, ad-free version that is easily accessible. The implementation should include smooth animations, intuitive controls, and options for users to customize the game difficulty. The game should be lightweight and responsive, ensuring a seamless user experience.

### Use Case

**Casual Gaming:**
1. User opens the game.
2. Game loads quickly without ads.
3. User plays using simple, responsive controls.
4. Smooth animations enhance gameplay.
5. User can adjust difficulty level.

**Skill Improvement:**
1. User selects the game.
2. User chooses higher difficulty.
3. User plays, navigating obstacles.
4. High scores track improvement.

**Customization Enthusiasts:**
1. User accesses the game.
2. User customizes bird and background themes.
3. User starts the game with personalized settings.
4. Smooth animations and intuitive controls provide a great experience.

**Educational Use:**
1. Teacher shares the game with students.
2. Students play and analyze game mechanics.
3. Teacher explains coding concepts.
4. Students modify game settings through basic coding.

**Accessibility Needs:**
1. User opens the game.
2. User adjusts settings for accessibility (e.g., slower speed, higher contrast).
3. User plays with intuitive, responsive controls.
4. User enjoys an accessible and seamless experience.

### Benefits

1. Engaging Gameplay: Smooth animations and intuitive controls make the game enjoyable.
2. Customizable Experience: Users can adjust difficulty levels and personalize themes.
3. Ad-Free: Provides an uninterrupted, clean gaming experience.
4. Lightweight and Fast: Quick loading times and responsiveness enhance user satisfaction.
5. Educational Value: Can be used as a tool to teach basic programming concepts.
6. Accessible: Adjustable settings ensure the game is playable for users with different needs.

### Add ScreenShots

![120](https://github.com/SyedImtiyaz-1/GetTechProjects/assets/146121869/76915efb-298b-4a88-820f-8595247a0e99)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by SakiraAli1115** [comment]
Hello PA,
@SyedImtiyaz-1 
Can you please assign me this issue!
