### ISSUE TITLE
[New Project]: Attendance Tracker 

### ISSUE THREAD

**Issue by anisharma07** [SyedImtiyaz-1/GetTechProjects#925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

A web app which allows students to keep track of their attendance for their classes...

### Use Case

- users can see the attendance record marked by them and the total no. of classes occured
- users can add multiples subjects for keeping the attendance

### Add ScreenShots

![image](https://github.com/user-attachments/assets/ec9a5980-9ff4-4978-81e4-4ef38be40c6a)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by unnati-078** [comment]
Hi, I hope you're doing well. I am a contributor for GirlScript Summer of Code Extended Edition and would love to work on this issue. Could you please assign it to me? Thank you!
