### ISSUE TITLE
[Bug]: Adjust Chatbot Position for Better Visibility

### ISSUE THREAD

**Issue by snehhhcodes** [SyedImtiyaz-1/GetTechProjects#944]
### Is there an existing issue for this? No

- [X] I have searched the existing issues

### Describe the bug

The chatbot is currently positioned too high on the screen, making it difficult for users to see it properly and interact with it fully. This can lead to a poor user experience, as users may overlook the chatbot or find it inconvenient to use.
![Screenshot 2024-10-02 123056](https://github.com/user-attachments/assets/70690bf7-f1ce-40c7-8f15-0bcf463ea7f5)

### Expected behavior

To improve the visibility of the chatbot, I will reposition it slightly lower on the screen. This adjustment will ensure that users can see the chatbot more easily and interact with it without obstruction.

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AshutoshKumar0206** [comment]
Assign me this issue. I will work on it.

**Comment by aryan04dbz** [comment]
I solved this issue by changing the value from 100px to 90px

**Comment by snehhhcodes** [comment]
@SyedImtiyaz-1 any update on this?

**Comment by AshutoshKumar0206** [comment]
Can I work on this. I just have to change the css of it and it will be fine.

**Comment by snehhhcodes** [comment]
this repo is inactive since three months so thts why i closed the issue by myself
